### ISSUE TITLE
Update S3BackMode in SplunkDestinationConfiguration

### ISSUE THREAD

**Issue by abarnwal13** [awsdocs/amazon-kinesis-data-firehose-developer-guide#11]
Hi team,
I am facing this issue while updating the S3BackMode from AllEvents to FailedOnlyEvents. As per documentation best practice is to enable AllEvents first and check if the events are available on Splunk index and then you can change it to FailedEventsOnly. When I tried updating S3BackMode to FailedEventsOnly using same cloudformation it throws error.
`Disabling S3 backup is not currently supported. (Service: AmazonKinesisFirehose; Status Code: 400; Error Code: InvalidArgumentException; Request ID: f5cf3d67-8faf-b96d-a32b-77ff85835cac)`
Also, I tried going to AWS Console to update the value and found that field is not modifiable. This is very frustrating that going through the best practices will lead us to this problem. 

Firehose documentation is also confusing with the allowed values for this configuration. It is documented as **FailedDocumentsOnly** and **AllDocuments** but Allowed Values for S3BackupMode **AllEvents | FailedEventsOnly**. Please refer below information copied form documentation.
https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-splunkdestinationconfiguration.html#cfn-kinesisfirehose-deliverystream-splunkdestinationconfiguration-s3backupmode
`When set to FailedDocumentsOnly, Kinesis Data Firehose writes any data that could not be indexed to the configured Amazon S3 destination. When set to AllDocuments, Kinesis Data Firehose delivers all incoming records to Amazon S3, and also writes failed documents to Amazon S3. Default value is FailedDocumentsOnly.`

**Comment by Gaianab** [comment]
customer is describing by default behavior. But I'll open a SIM and assign to engineering to investigate.
