### ISSUE TITLE
Issue with option aggregatedRecordSizeBytes

### ISSUE THREAD

**Issue by gfediere** [awsdocs/amazon-kinesis-data-firehose-developer-guide#12]
Hi,

The option: aggregatedRecordSizeBytes is mentioned in the official English documentation: https://docs.aws.amazon.com/firehose/latest/dev/writing-with-agents.html. Weird thing is this option is not written anymore in the writing-with-agents.md and not present in translated page (french, spanish, ...)
Does this option really exist ?

Br,

**Comment by Gaianab** [comment]
thanks for the feedback! I'll open a SIM to investigate.
