### ISSUE TITLE
No mention of schema on data transformation page

### ISSUE THREAD

**Issue by nanodeath** [awsdocs/amazon-kinesis-data-firehose-developer-guide#15]
Hi,

I came across [this page](https://github.com/awsdocs/amazon-kinesis-data-firehose-developer-guide/blob/1216899a21b7d1dcbf1549f0e0ec2c4059b66fa1/doc_source/data-transformation.md) with the goal of learning how transformations worked. Specifically, as a user of the AWS SDK for Java v2, I'm trying to figure out _how_ to actually write a data transformation using Lambda. However...the page seems to be lacking documentation on that subject. It covers the expected return value from the Lambda, but doesn't discuss what data is passed to the Lambda, nor what interfaces I should be using or example snippets. Any of these would be super helpful to getting started.

**Comment by Gaianab** [comment]
thanks for the feedback, I'll open a SIM and will assign to the appropriate member of the engineering team.
