### ISSUE TITLE
Missing screenshots for the permissions link and role creation.

### ISSUE THREAD

**Issue by labeveryday** [awsdocs/amazon-kinesis-data-firehose-developer-guide#25]
The screenshots that are mentioned in the documentation are missing. This does not show how the permissions for the role should be configured. https://github.com/awsdocs/amazon-kinesis-data-firehose-developer-guide/blob/master/doc_source/log-data-from-vpc-to-cw.md

**Comment by Gaianab** [comment]
thanks for your feedback! I'm removing this outdated screenshot and updating the steps.
