### ISSUE TITLE
Broken images links

### ISSUE THREAD

**Issue by eisraeli** [awsdocs/amazon-kinesis-data-firehose-developer-guide#27]
Hi,
This issue is about the following MD file:
https://github.com/awsdocs/amazon-kinesis-data-firehose-developer-guide/blob/master/doc_source/log-data-from-vpc-to-cw.md

In the `To create a VPC flow log` section, steps 7 and 8 contain the following images:
```
1. To set up an IAM role, choose **Set Up Permissions**\.   
![\[Screenshot showing the Set Up Permissions link.\]](http://docs.aws.amazon.com/firehose/latest/dev/images/firehose-createflowlog-console.png)

1. In the new window that appears, keep **IAM Role** set to **Create a new IAM Role**\. In the **Role Name** box, enter **VPCtoSplunkWritetoCWRole**\. Then choose **Allow**\.  
![\[Screenshot showing creating the role named VPCtoSplunkWritetoCWRole.\]](http://docs.aws.amazon.com/firehose/latest/dev/images/firehose-cwflowlogrole-console.png)
```

Those images are not available using those URLs and therefore will not load as part of the markdown page.
Making an HTTP request to retrieve them will result in a access denied error.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
