### ISSUE TITLE
Error in timestamp string

### ISSUE THREAD

**Issue by aahaselgrove** [awsdocs/amazon-kinesis-data-firehose-developer-guide#8]
On [s3-prefixes.md](https://github.com/awsdocs/amazon-kinesis-data-firehose-developer-guide/blob/master/doc_source/s3-prefixes.md), one example timestamp string is `'year='yyyy'/month='MM'/day='dd'/hour='HH'`. This is not a valid timestamp string. It should be `'year='yyyy'/month='MM'/day='dd'/hour='HH`

**Comment by Gaianab** [comment]
this has been fixed.
